// Barrel file: re-exports all inventory modules
// Each sub-module has its own 'use server' directive

export {
  type ProductType,
  type StockStatus,
  type ProductCategoryData,
  type ProductData,
  type ProductListItemData,
  type InventoryStats,
  type CreateProductInput,
  getProductCategories,
  createProductCategory,
  initializeDefaultCategories,
  getProducts,
  getProductById,
  createProduct,
  updateProduct,
  deleteProduct,
  getInventoryStats,
  searchProducts,
} from './inventory-products'

export {
  type LotStatus,
  type ProductLotData,
  type LotListItemData,
  type LotStats,
  type ProductForLot,
  type SupplierForLot,
  getProductLots,
  createProductLot,
  getLotsForList,
  deleteLot,
  getLotStats,
  getProductsForLots,
  getSuppliersForLots,
} from './inventory-lots'

export {
  type SupplierData,
  type SupplierStats,
  getSuppliers,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  getSupplierStats,
} from './inventory-suppliers'

export {
  type PurchaseOrderStatus,
  type PaymentStatus,
  type PurchaseOrderData,
  type PurchaseOrderItemData,
  type PurchaseOrderStats,
  getPurchaseOrders,
  getPurchaseOrderById,
  getPurchaseOrderItems,
  createPurchaseOrder,
  updatePurchaseOrderStatus,
  deletePurchaseOrder,
  getPurchaseOrderStats,
} from './inventory-orders'

export {
  type InventoryCountType,
  type InventoryCountStatus,
  type InventoryCountData,
  type InventoryCountItemData,
  type InventoryCountStats,
  type TransferStatus,
  type InventoryTransferData,
  type TransferItemData,
  type TransferStats,
  type BranchData,
  getInventoryCounts,
  getInventoryCountById,
  getInventoryCountItems,
  createInventoryCount,
  updateInventoryCountItem,
  completeInventoryCount,
  deleteInventoryCount,
  getInventoryCountStats,
  getInventoryTransfers,
  getInventoryTransferById,
  getTransferItems,
  createInventoryTransfer,
  updateTransferStatus,
  deleteInventoryTransfer,
  getTransferStats,
  getBranches,
} from './inventory-stock'
