// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Clinics & Branches
      clinics: {
        Row: {
          id: string
          name: string
          legal_name: string | null
          logo_url: string | null
          primary_color: string | null
          timezone: string
          currency: string
          tax_id: string | null
          address: string | null
          city: string | null
          state: string | null
          postal_code: string | null
          country: string | null
          phone: string | null
          email: string | null
          website: string | null
          instagram: string | null
          facebook: string | null
          settings: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          legal_name?: string | null
          logo_url?: string | null
          primary_color?: string | null
          timezone?: string
          currency?: string
          tax_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          phone?: string | null
          email?: string | null
          website?: string | null
          instagram?: string | null
          facebook?: string | null
          settings?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          legal_name?: string | null
          logo_url?: string | null
          primary_color?: string | null
          timezone?: string
          currency?: string
          tax_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          phone?: string | null
          email?: string | null
          website?: string | null
          instagram?: string | null
          facebook?: string | null
          settings?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      branches: {
        Row: {
          id: string
          clinic_id: string
          name: string
          address: string | null
          phone: string | null
          email: string | null
          manager_id: string | null
          rooms_count: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          name: string
          address?: string | null
          phone?: string | null
          email?: string | null
          manager_id?: string | null
          rooms_count?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          name?: string
          address?: string | null
          phone?: string | null
          email?: string | null
          manager_id?: string | null
          rooms_count?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      // Users
      users: {
        Row: {
          id: string
          clinic_id: string
          email: string
          first_name: string
          last_name: string
          phone: string | null
          avatar_url: string | null
          role: string
          specialties: string[] | null
          certifications: string[] | null
          bio: string | null
          allowed_treatment_ids: string[] | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          clinic_id: string
          email: string
          first_name: string
          last_name: string
          phone?: string | null
          avatar_url?: string | null
          role?: string
          specialties?: string[] | null
          certifications?: string[] | null
          bio?: string | null
          allowed_treatment_ids?: string[] | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          email?: string
          first_name?: string
          last_name?: string
          phone?: string | null
          avatar_url?: string | null
          role?: string
          specialties?: string[] | null
          certifications?: string[] | null
          bio?: string | null
          allowed_treatment_ids?: string[] | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      // Patients
      patients: {
        Row: {
          id: string
          clinic_id: string
          first_name: string
          last_name: string
          email: string | null
          phone: string
          phone_secondary: string | null
          date_of_birth: string | null
          gender: string | null
          document_type: string | null
          document_number: string | null
          address: string | null
          city: string | null
          state: string | null
          postal_code: string | null
          country: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          preferred_contact: string | null
          preferred_schedule: Json | null
          source: string | null
          referred_by_id: string | null
          tags: string[] | null
          status: string
          notes: string | null
          avatar_url: string | null
          total_spent: number
          visit_count: number
          last_visit_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          clinic_id: string
          first_name: string
          last_name: string
          email?: string | null
          phone: string
          phone_secondary?: string | null
          date_of_birth?: string | null
          gender?: string | null
          document_type?: string | null
          document_number?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          preferred_contact?: string | null
          preferred_schedule?: Json | null
          source?: string | null
          referred_by_id?: string | null
          tags?: string[] | null
          status?: string
          notes?: string | null
          avatar_url?: string | null
          total_spent?: number
          visit_count?: number
          last_visit_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          clinic_id?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string
          phone_secondary?: string | null
          date_of_birth?: string | null
          gender?: string | null
          document_type?: string | null
          document_number?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          preferred_contact?: string | null
          preferred_schedule?: Json | null
          source?: string | null
          referred_by_id?: string | null
          tags?: string[] | null
          status?: string
          notes?: string | null
          avatar_url?: string | null
          total_spent?: number
          visit_count?: number
          last_visit_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      // Treatments
      treatments: {
        Row: {
          id: string
          clinic_id: string | null
          category_id: string | null
          name: string
          slug: string
          description: string | null
          description_internal: string | null
          duration_minutes: number
          buffer_minutes: number
          price: number
          price_from: number | null
          cost: number
          currency: 'DOP' | 'USD'
          recommended_sessions: number
          session_interval_days: number | null
          contraindications: string[]
          aftercare_instructions: string | null
          required_consent_id: string | null
          allowed_professional_ids: string[]
          required_room_types: string[]
          required_equipment_ids: string[]
          consumables: { productId: string; quantity: number }[]
          protocol_steps: { order: number; title: string; description?: string; durationMinutes?: number }[]
          image_url: string | null
          gallery_urls: string[]
          is_public: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          clinic_id?: string | null
          category_id?: string | null
          name: string
          slug: string
          description?: string | null
          description_internal?: string | null
          duration_minutes: number
          buffer_minutes?: number
          price: number
          price_from?: number | null
          cost?: number
          currency?: 'DOP' | 'USD'
          recommended_sessions?: number
          session_interval_days?: number | null
          contraindications?: string[]
          aftercare_instructions?: string | null
          required_consent_id?: string | null
          allowed_professional_ids?: string[]
          required_room_types?: string[]
          required_equipment_ids?: string[]
          consumables?: { productId: string; quantity: number }[]
          protocol_steps?: { order: number; title: string; description?: string; durationMinutes?: number }[]
          image_url?: string | null
          gallery_urls?: string[]
          is_public?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string | null
          category_id?: string | null
          name?: string
          slug?: string
          description?: string | null
          description_internal?: string | null
          duration_minutes?: number
          buffer_minutes?: number
          price?: number
          price_from?: number | null
          cost?: number
          currency?: 'DOP' | 'USD'
          recommended_sessions?: number
          session_interval_days?: number | null
          contraindications?: string[]
          aftercare_instructions?: string | null
          required_consent_id?: string | null
          allowed_professional_ids?: string[]
          required_room_types?: string[]
          required_equipment_ids?: string[]
          consumables?: { productId: string; quantity: number }[]
          protocol_steps?: { order: number; title: string; description?: string; durationMinutes?: number }[]
          image_url?: string | null
          gallery_urls?: string[]
          is_public?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      // Packages
      packages: {
        Row: {
          id: string
          clinic_id: string | null
          name: string
          description: string | null
          total_sessions: number
          price: number
          currency: 'DOP' | 'USD'
          validity_days: number
          is_active: boolean
          treatments: { treatment_id: string; quantity: number }[]
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id?: string | null
          name: string
          description?: string | null
          total_sessions: number
          price: number
          currency?: 'DOP' | 'USD'
          validity_days?: number
          is_active?: boolean
          treatments: { treatment_id: string; quantity: number }[]
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string | null
          name?: string
          description?: string | null
          total_sessions?: number
          price?: number
          currency?: 'DOP' | 'USD'
          validity_days?: number
          is_active?: boolean
          treatments?: { treatment_id: string; quantity: number }[]
          created_at?: string
        }
      }
      // Patient Medical History
      patient_medical_history: {
        Row: {
          id: string
          patient_id: string
          allergies: string[]
          current_medications: string[]
          chronic_conditions: string[]
          previous_surgeries: string[]
          previous_aesthetic_treatments: string[]
          is_pregnant: boolean
          is_breastfeeding: boolean
          uses_retinoids: boolean
          sun_exposure_level: string
          additional_notes: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          allergies?: string[]
          current_medications?: string[]
          chronic_conditions?: string[]
          previous_surgeries?: string[]
          previous_aesthetic_treatments?: string[]
          is_pregnant?: boolean
          is_breastfeeding?: boolean
          uses_retinoids?: boolean
          sun_exposure_level?: string
          additional_notes?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          allergies?: string[]
          current_medications?: string[]
          chronic_conditions?: string[]
          previous_surgeries?: string[]
          previous_aesthetic_treatments?: string[]
          is_pregnant?: boolean
          is_breastfeeding?: boolean
          uses_retinoids?: boolean
          sun_exposure_level?: string
          additional_notes?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

// Specific types for convenience
export type Clinic = Tables<'clinics'>
export type Branch = Tables<'branches'>
export type User = Tables<'users'>
export type Patient = Tables<'patients'>
